// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxrqbmifotfshfkbgkbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cnFibWlmb3Rmc2hma2Jna2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTE1NTIsImV4cCI6MjA1ODU2NzU1Mn0.2ArEqX8DzBMtCddwSvRLM1UMn-Q7kQizAvsJO5wNqvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);